(function () {
  const intervalOptions = [
    { value: '', label: 'Choose an interval' },
    { value: 'all-real', label: 'All real numbers, (-∞, ∞)' },
    { value: 'x>0', label: '(0, ∞)' },
    { value: 'x>=0', label: '[0, ∞)' },
    { value: 'y>0', label: '(0, ∞)' },
    { value: 'y>=0', label: '[0, ∞)' },
    { value: 'y!=0', label: 'All real numbers except 0' }
  ];

  const parentOptions = [
    'quadratic', 'linear', 'logarithmic', 'exponential', 'square-root',
    'cubic', 'reciprocal', 'reciprocal-squared', 'absolute-value', 'cube-root'
  ].map((value) => ({ value, label: value.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ') }));

  const graphFields = {
    parent: { label: 'Parent function family', type: 'select', options: [{ value: '', label: 'Choose a family' }, ...parentOptions] },
    domain: { label: 'Domain', type: 'select', options: intervalOptions },
    range: { label: 'Range', type: 'select', options: intervalOptions },
    vertex: { label: 'Vertex / turning point', type: 'point', placeholder: '(0,0)' },
    keyPoint: { label: 'Key point or intercept', type: 'point', placeholder: '(0,0)' },
    startPoint: { label: 'Starting point', type: 'point', placeholder: '(0,0)' },
    centerPoint: { label: 'Center point', type: 'point', placeholder: '(0,0)' },
    verticalAsymptote: { label: 'Vertical asymptote', type: 'select', options: [{ value: '', label: 'Choose one' }, { value: 'none', label: 'None' }, { value: 'x=0', label: 'x = 0' }] },
    horizontalAsymptote: { label: 'Horizontal asymptote', type: 'select', options: [{ value: '', label: 'Choose one' }, { value: 'none', label: 'None' }, { value: 'y=0', label: 'y = 0' }] },
    opening: { label: 'Opening / branch direction', type: 'select', options: [
      { value: '', label: 'Choose a direction' },
      { value: 'up', label: 'Opens up' },
      { value: 'both', label: 'Two opposite branches' },
      { value: 'quadrants-i-iii', label: 'Branches in Quadrants I and III' },
      { value: 'above-axis-both-sides', label: 'Above x-axis on both sides of y-axis' },
      { value: 'v-up', label: 'V opens up' },
      { value: 'line-rising', label: 'Rises left to right' },
      { value: 's-curve', label: 'S-shaped through origin' },
      { value: 'starts-right-up', label: 'Starts at origin and goes right/up' }
    ] },
    reflection: { label: 'Reflection from the usual parent graph?', type: 'checkbox' },
    slope: { label: 'Slope', type: 'text', placeholder: '4/3' },
    yIntercept: { label: 'y-intercept', type: 'point', placeholder: '(0,-2)' }
  };

  const P = 'Part 1';
  const E = 'Part 2';
  const G = 'Part 3';

  window.FINAL_REVIEW_PROBLEMS = [
    { id: '1', part: P, skillTags: ['quadratic equations', 'factoring'], promptLatex: '\\(5x^2+9x+15=4x^2+1\\)', answerType: 'expressionSet', correctAnswer: ['-7', '-2'], startBy: 'Move every term to one side so the equation is equal to 0.', hint: 'After subtracting the right side, factor x² + 9x + 14.', feedback: { correct: 'Correct: both factors give the listed x-values.', incorrect: 'Check that your answer includes both roots and no extra text.' } },
    { id: '2', part: P, skillTags: ['quadratic equations', 'factoring'], promptLatex: '\\(2x^2+5x-10=2x-1\\)', answerType: 'expressionSet', correctAnswer: ['3/2', '-3'], startBy: 'Move all terms to one side and combine like terms.', hint: 'You should get 2x² + 3x - 9 = 0.', feedback: { correct: 'Correct. The factors lead to x = -3 and x = 3/2.', incorrect: 'Try factoring 2x² + 3x - 9 or use the quadratic formula.' } },
    { id: '3', part: P, skillTags: ['polynomial equations', 'factoring by grouping'], promptLatex: '\\(x^3+x^2-x-1=0\\)', answerType: 'expressionSet', correctAnswer: ['-1', '1'], startBy: 'Group the first two terms and the last two terms.', hint: 'Factor by grouping: x²(x + 1) - 1(x + 1).', feedback: { correct: 'Correct. x = -1 is repeated, but list it once.', incorrect: 'Look for a common binomial after grouping.' } },
    { id: '4', part: P, skillTags: ['polynomial equations', 'factoring by grouping'], promptLatex: '\\(x^3-4x^2-x+4=0\\)', answerType: 'expressionSet', correctAnswer: ['-1', '1', '4'], startBy: 'Group the first two terms and the last two terms.', hint: 'Factor x²(x - 4) - 1(x - 4).', feedback: { correct: 'Correct. All three linear factors give roots.', incorrect: 'After grouping, factor the difference of squares.' } },
    { id: '5', part: P, skillTags: ['logarithmic equations'], promptLatex: '\\(-9\\log_6(-4x)=-18\\)', answerType: 'numeric', correctAnswer: -9, startBy: 'Divide both sides by -9 before rewriting in exponential form.', hint: 'log₆(-4x) = 2 means -4x = 6².', feedback: { correct: 'Correct. The log argument is positive when x = -9.', incorrect: 'Remember that -4x is the log argument.' } },
    { id: '6', part: P, skillTags: ['logarithmic equations', 'domain restrictions'], promptLatex: '\\(\\log_2(x+6)+\\log_2(x)=4\\)', answerType: 'numeric', correctAnswer: 2, startBy: 'Use the product property for logs, then check the domain.', hint: 'log₂(x(x + 6)) = 4, so x(x + 6) = 16.', feedback: { correct: 'Correct. The negative quadratic solution is outside the log domain.', incorrect: 'Do not keep a solution that makes x or x + 6 nonpositive.' } },
    { id: '7', part: P, skillTags: ['absolute value equations'], promptLatex: '\\(|2x-4|+3=11\\)', answerType: 'expressionSet', correctAnswer: ['-2', '6'], startBy: 'Isolate the absolute value before splitting into two equations.', hint: '|2x - 4| = 8, so 2x - 4 = 8 or 2x - 4 = -8.', feedback: { correct: 'Correct. Both values make the absolute value equal 8.', incorrect: 'Remember to solve both the positive and negative cases.' } },
    { id: '8', part: P, skillTags: ['exponential equations'], promptLatex: '\\(9^{-x}=27\\)', answerType: 'numeric', correctAnswer: -1.5, accepted: ['-3/2'], startBy: 'Rewrite both sides with base 3.', hint: '9 is 3² and 27 is 3³, so 3^(-2x) = 3³.', feedback: { correct: 'Correct. Matching exponents gives x = -3/2.', incorrect: 'Use the same base before setting exponents equal.' } },
    { id: '9', part: P, skillTags: ['exponential equations'], promptLatex: '\\(4^{2-2x}=\\frac{1}{8}\\)', answerType: 'numeric', correctAnswer: 1.75, accepted: ['7/4'], startBy: 'Rewrite both sides with base 2.', hint: '4^(2 - 2x) = 2^(4 - 4x), and 1/8 = 2^-3.', feedback: { correct: 'Correct. 4 - 4x = -3.', incorrect: 'Check the exponent when changing 4 to base 2.' } },
    { id: '10', part: P, skillTags: ['radical equations', 'rational exponents'], promptLatex: '\\(9=1-(x-15)^{3/5}\\)', answerType: 'numeric', correctAnswer: -17, startBy: 'Isolate the rational exponent expression.', hint: '(x - 15)^(3/5) = -8. Think of the fifth root first.', feedback: { correct: 'Correct. The fifth-root value is -2, so x - 15 = -32.', incorrect: 'For real fifth roots, negative inputs are allowed.' } },
    { id: '11', part: P, skillTags: ['rational exponents', 'factoring'], promptLatex: '\\(x^{4/5}+3x^{9/5}=0\\)', answerType: 'expressionSet', correctAnswer: ['0', '-1/3'], startBy: 'Factor out the common power x^(4/5).', hint: 'x^(9/5) = x·x^(4/5), so factor x^(4/5)(1 + 3x).', feedback: { correct: 'Correct. Each factor can equal 0.', incorrect: 'Use the zero product property after factoring.' } },
    { id: '12', part: P, skillTags: ['rational equations', 'extraneous solutions'], promptLatex: '\\(\\frac{1}{x^2-x}=\\frac{-2x+3}{x-1}\\)', answerType: 'numeric', correctAnswer: 0.5, accepted: ['1/2'], startBy: 'State the restrictions, then multiply by x(x - 1).', hint: 'x cannot be 0 or 1. Multiplying through gives 1 = x(-2x + 3).', feedback: { correct: 'Correct. x = 1 is extraneous because it is not in the domain, so x = 1/2.', incorrect: 'Check restrictions after solving.' } },
    { id: '13', part: P, skillTags: ['rational equations', 'no solution'], promptLatex: '\\(\\frac{1}{x^2-3x+2}=\\frac{1}{x^2-3x+2}-\\frac{1}{x-1}\\)', answerType: 'multipleChoice', correctAnswer: 'no-solution', startBy: 'Subtract the matching fraction from both sides.', hint: 'The equation becomes 0 = -1/(x - 1), which cannot happen.', choices: [{ value: 'x=1', label: 'x = 1' }, { value: 'x=2', label: 'x = 2' }, { value: 'no-solution', label: 'No solution' }, { value: 'all-real', label: 'All real numbers except 1 and 2' }], feedback: { correct: 'Correct. There is no value that makes the remaining fraction equal 0.', incorrect: 'Also remember x = 1 and x = 2 are excluded from the original denominator.' } },

    { id: '14', part: E, skillTags: ['order of operations'], promptLatex: '\\(8-16\\div4\\)', answerType: 'numeric', correctAnswer: 4, startBy: 'Divide before subtracting.', hint: '16 ÷ 4 = 4.', feedback: { correct: 'Correct.', incorrect: 'Use order of operations: division comes before subtraction.' } },
    { id: '15', part: E, skillTags: ['rational exponents', 'radicals'], promptLatex: '\\(81^{1/4}\\)', answerType: 'numeric', correctAnswer: 3, startBy: 'A 1/4 exponent means fourth root.', hint: '3⁴ = 81.', feedback: { correct: 'Correct.', incorrect: 'Find the positive principal fourth root.' } },
    { id: '16', part: E, skillTags: ['exponents', 'order of operations'], promptLatex: '\\(-4^2\\)', answerType: 'numeric', correctAnswer: -16, startBy: 'Apply the exponent before the leading negative.', hint: '-4² means -(4²), not (-4)².', feedback: { correct: 'Correct.', incorrect: 'Parentheses would be needed to square the negative.' } },
    { id: '17', part: E, skillTags: ['integer exponents'], promptLatex: '\\((-3)^3\\)', answerType: 'numeric', correctAnswer: -27, startBy: 'The negative number is inside parentheses.', hint: 'A negative cubed stays negative.', feedback: { correct: 'Correct.', incorrect: 'Multiply (-3)(-3)(-3).' } },
    { id: '18', part: E, skillTags: ['fractions', 'reciprocals'], promptLatex: '\\(\\frac{1}{5/9}\\)', answerType: 'numeric', correctAnswer: 1.8, accepted: ['9/5'], startBy: 'Dividing by a fraction means multiplying by its reciprocal.', hint: '1 ÷ (5/9) = 1 · 9/5.', feedback: { correct: 'Correct.', incorrect: 'Use the reciprocal of 5/9.' } },
    { id: '19', part: E, skillTags: ['integer exponents'], promptLatex: '\\((-4)^4\\)', answerType: 'numeric', correctAnswer: 256, startBy: 'The base -4 is in parentheses.', hint: 'An even power of a negative number is positive.', feedback: { correct: 'Correct.', incorrect: 'Compute (-4)(-4)(-4)(-4).' } },
    { id: '20', part: E, skillTags: ['negative exponents'], promptLatex: '\\(29^{-1}\\)', answerType: 'numeric', correctAnswer: 1 / 29, accepted: ['1/29'], startBy: 'A -1 exponent means reciprocal.', hint: 'a^-1 = 1/a.', feedback: { correct: 'Correct.', incorrect: 'Do not make it negative; make it a reciprocal.' } },
    { id: '21', part: E, skillTags: ['radicals'], promptLatex: '\\(\\sqrt[4]{32}\\)', answerType: 'multipleChoice', correctAnswer: '2-fourth-root-2', startBy: 'Factor 32 using a perfect fourth power.', hint: '32 = 16 · 2, and the fourth root of 16 is 2.', choices: [{ value: '2-fourth-root-2', label: '2 fourth-root 2' }, { value: '4-root-2', label: '4√2' }, { value: '2-root-2', label: '2√2' }, { value: '8', label: '8' }], feedback: { correct: 'Correct. The simplified exact form is 2 fourth-root 2.', incorrect: 'Only groups of four identical factors come out of a fourth root.' } },
    { id: '22', part: E, skillTags: ['negative exponents', 'rational exponents'], promptLatex: '\\(8^{-1/3}\\)', answerType: 'numeric', correctAnswer: 0.5, accepted: ['1/2'], startBy: 'A 1/3 exponent means cube root; the negative exponent means reciprocal.', hint: 'The cube root of 8 is 2, then take the reciprocal.', feedback: { correct: 'Correct.', incorrect: 'Evaluate the cube root before applying the reciprocal.' } },
    { id: '23', part: E, skillTags: ['logarithms'], promptLatex: '\\(\\log_4(64)\\)', answerType: 'numeric', correctAnswer: 3, startBy: 'Ask: 4 to what power equals 64?', hint: '4³ = 64.', feedback: { correct: 'Correct.', incorrect: 'Rewrite the logarithm as an exponent equation.' } },
    { id: '24', part: E, skillTags: ['logarithms', 'negative exponents'], promptLatex: '\\(\\log_2\\left(\\frac{1}{16}\\right)\\)', answerType: 'numeric', correctAnswer: -4, startBy: 'Rewrite 1/16 as a power of 2.', hint: '1/16 = 2^-4.', feedback: { correct: 'Correct.', incorrect: 'The answer is negative because the argument is a fraction between 0 and 1.' } },
    { id: '25', part: E, skillTags: ['natural logarithms'], promptLatex: '\\(\\ln(e^4)\\)', answerType: 'numeric', correctAnswer: 4, startBy: 'ln and e are inverse operations.', hint: 'ln(e^k) = k.', feedback: { correct: 'Correct.', incorrect: 'The natural log has base e.' } },

    { id: '26', part: G, skillTags: ['graphing parent functions', 'quadratic graphs'], promptLatex: '\\(f(x)=x^2\\)', answerType: 'graphFeatures', desmosExpression: 'y=x^2', graphFields: ['parent', 'domain', 'range', 'vertex', 'opening', 'reflection'], correctAnswer: { parent: 'quadratic', domain: 'all-real', range: 'y>=0', vertex: [0, 0], opening: 'up', reflection: false }, startBy: 'Identify the parent family and its vertex before thinking about the rest of the graph.', hint: 'The basic parabola has vertex at the origin and opens upward.', feedback: { correct: 'Correct. This is the quadratic parent function.', incorrect: 'Check the vertex, domain, range, and opening direction.' } },
    { id: '27', part: G, skillTags: ['graphing parent functions', 'linear graphs'], promptLatex: '\\(g(x)=x\\)', answerType: 'graphFeatures', desmosExpression: 'y=x', graphFields: ['parent', 'domain', 'range', 'keyPoint', 'opening', 'reflection'], correctAnswer: { parent: 'linear', domain: 'all-real', range: 'all-real', keyPoint: [0, 0], opening: 'line-rising', reflection: false }, startBy: 'Recognize the identity linear function.', hint: 'It is a line through the origin with slope 1.', feedback: { correct: 'Correct. This is the identity line.', incorrect: 'Check that both domain and range are all real numbers.' } },
    { id: '28', part: G, skillTags: ['logarithmic graphs', 'asymptotes'], promptLatex: '\\(y=\\log_2(x)\\)', answerType: 'graphFeatures', desmosExpression: 'y=\\log_2(x)', graphFields: ['parent', 'domain', 'range', 'keyPoint', 'verticalAsymptote', 'horizontalAsymptote'], correctAnswer: { parent: 'logarithmic', domain: 'x>0', range: 'all-real', keyPoint: [1, 0], verticalAsymptote: 'x=0', horizontalAsymptote: 'none' }, startBy: 'Log graphs are only to the right of their vertical asymptote.', hint: 'The log parent graph passes through (1, 0) and has vertical asymptote x = 0.', feedback: { correct: 'Correct. Base 2 changes steepness but not these parent features.', incorrect: 'Check the domain and the vertical asymptote.' } },
    { id: '29', part: G, skillTags: ['exponential graphs', 'asymptotes'], promptLatex: '\\(y=3^x\\)', answerType: 'graphFeatures', desmosExpression: 'y=3^x', graphFields: ['parent', 'domain', 'range', 'keyPoint', 'verticalAsymptote', 'horizontalAsymptote'], correctAnswer: { parent: 'exponential', domain: 'all-real', range: 'y>0', keyPoint: [0, 1], verticalAsymptote: 'none', horizontalAsymptote: 'y=0' }, startBy: 'Exponential parent functions pass through (0, 1).', hint: 'There is no vertical asymptote, and the x-axis is a horizontal asymptote.', feedback: { correct: 'Correct. The base 3 exponential stays above the x-axis.', incorrect: 'Check the y-intercept and horizontal asymptote.' } },
    { id: '30', part: G, skillTags: ['square root graphs', 'domain and range'], promptLatex: '\\(f(x)=\\sqrt{x}\\)', answerType: 'graphFeatures', desmosExpression: 'y=\\sqrt{x}', graphFields: ['parent', 'domain', 'range', 'startPoint', 'opening', 'reflection'], correctAnswer: { parent: 'square-root', domain: 'x>=0', range: 'y>=0', startPoint: [0, 0], opening: 'starts-right-up', reflection: false }, startBy: 'A square-root graph starts where the radicand is 0.', hint: 'The parent square-root graph starts at the origin and goes right/up.', feedback: { correct: 'Correct. Both domain and range begin at 0.', incorrect: 'Check the starting point and intervals.' } },
    { id: '31', part: G, skillTags: ['cubic graphs'], promptLatex: '\\(h(x)=x^3\\)', answerType: 'graphFeatures', desmosExpression: 'y=x^3', graphFields: ['parent', 'domain', 'range', 'keyPoint', 'opening', 'reflection'], correctAnswer: { parent: 'cubic', domain: 'all-real', range: 'all-real', keyPoint: [0, 0], opening: 's-curve', reflection: false }, startBy: 'Think of the basic S-shaped cubic parent graph.', hint: 'The cubic parent passes through the origin and has no domain or range restrictions.', feedback: { correct: 'Correct. The cubic parent is all real for both domain and range.', incorrect: 'Check that the graph continues forever in both directions.' } },
    { id: '32', part: G, skillTags: ['reciprocal graphs', 'asymptotes'], promptLatex: '\\(f(x)=\\frac{1}{x}\\)', answerType: 'graphFeatures', desmosExpression: 'y=1/x', graphFields: ['parent', 'domain', 'range', 'opening', 'verticalAsymptote', 'horizontalAsymptote'], correctAnswer: { parent: 'reciprocal', domain: 'y!=0', range: 'y!=0', opening: 'quadrants-i-iii', verticalAsymptote: 'x=0', horizontalAsymptote: 'y=0' }, startBy: 'Find where the denominator is 0, then identify both asymptotes.', hint: 'The reciprocal parent has branches in Quadrants I and III.', feedback: { correct: 'Correct. x = 0 and y = 0 are asymptotes.', incorrect: 'For this parent, both x and y cannot be 0.' } },
    { id: '33', part: G, skillTags: ['reciprocal squared graphs', 'asymptotes'], promptLatex: '\\(g(x)=\\frac{1}{x^2}\\)', answerType: 'graphFeatures', desmosExpression: 'y=1/x^2', graphFields: ['parent', 'domain', 'range', 'opening', 'verticalAsymptote', 'horizontalAsymptote'], correctAnswer: { parent: 'reciprocal-squared', domain: 'y!=0', range: 'y>0', opening: 'above-axis-both-sides', verticalAsymptote: 'x=0', horizontalAsymptote: 'y=0' }, startBy: 'Squaring the denominator keeps the outputs positive.', hint: 'Both branches are above the x-axis, one on each side of the y-axis.', feedback: { correct: 'Correct. The graph never touches either axis.', incorrect: 'Check the range and branch location.' } },
    { id: '34', part: G, skillTags: ['logarithmic graphs', 'asymptotes'], promptLatex: '\\(y=\\log(x)\\)', answerType: 'graphFeatures', desmosExpression: 'y=\\log(x)', graphFields: ['parent', 'domain', 'range', 'keyPoint', 'verticalAsymptote', 'horizontalAsymptote'], correctAnswer: { parent: 'logarithmic', domain: 'x>0', range: 'all-real', keyPoint: [1, 0], verticalAsymptote: 'x=0', horizontalAsymptote: 'none' }, startBy: 'Treat log(x) as the common-log parent function.', hint: 'Like other log parents, it passes through (1, 0) and has x = 0 as a vertical asymptote.', feedback: { correct: 'Correct. Changing the base changes scale, not these features.', incorrect: 'Check the log parent function features.' } },
    { id: '35', part: G, skillTags: ['absolute value graphs'], promptLatex: '\\(y=|x|\\)', answerType: 'graphFeatures', desmosExpression: 'y=abs(x)', graphFields: ['parent', 'domain', 'range', 'vertex', 'opening', 'reflection'], correctAnswer: { parent: 'absolute-value', domain: 'all-real', range: 'y>=0', vertex: [0, 0], opening: 'v-up', reflection: false }, startBy: 'Absolute value parent graphs make a V shape.', hint: 'The vertex is at the origin and the V opens upward.', feedback: { correct: 'Correct. This is the absolute value parent graph.', incorrect: 'Check the vertex, range, and V direction.' } },
    { id: '36', part: G, skillTags: ['cube root graphs'], promptLatex: '\\(f(x)=\\sqrt[3]{x}\\)', answerType: 'graphFeatures', desmosExpression: 'y=\\sqrt[3]{x}', graphFields: ['parent', 'domain', 'range', 'keyPoint', 'opening', 'reflection'], correctAnswer: { parent: 'cube-root', domain: 'all-real', range: 'all-real', keyPoint: [0, 0], opening: 's-curve', reflection: false }, startBy: 'A cube-root graph is the inverse-shaped partner of a cubic graph.', hint: 'It passes through the origin and extends forever left/right and down/up.', feedback: { correct: 'Correct. Domain and range are all real.', incorrect: 'Check whether cube roots allow negative inputs.' } },
    { id: '37', part: G, skillTags: ['linear graphs', 'slope-intercept form'], promptLatex: '\\(y=\\frac{4}{3}x-2\\)', answerType: 'graphFeatures', desmosExpression: 'y=(4/3)x-2', graphFields: ['parent', 'domain', 'range', 'slope', 'yIntercept', 'opening'], correctAnswer: { parent: 'linear', domain: 'all-real', range: 'all-real', slope: '4/3', yIntercept: [0, -2], opening: 'line-rising' }, startBy: 'Use slope-intercept form y = mx + b.', hint: 'The slope is 4/3 and the y-intercept is (0, -2).', feedback: { correct: 'Correct. The positive slope makes the line rise left to right.', incorrect: 'Check m and b in y = mx + b.' } }
  ];

  window.FINAL_REVIEW_GRAPH_FIELDS = graphFields;
})();
