window.FINAL_REVIEW_SOLUTIONS = {
  '1': 'Move all terms left: x² + 9x + 14 = 0. Factor to (x + 7)(x + 2) = 0, so x = -7 or -2.',
  '2': 'Move all terms left: 2x² + 3x - 9 = 0. Factor to (2x - 3)(x + 3) = 0, so x = 3/2 or -3.',
  '3': 'Group terms: x²(x + 1) - 1(x + 1) = (x + 1)(x² - 1). The roots are -1 and 1.',
  '4': 'Group terms: x²(x - 4) - 1(x - 4) = (x - 4)(x² - 1), so x = 4, 1, or -1.',
  '5': 'Divide by -9 to get log₆(-4x) = 2. Then -4x = 36 and x = -9.',
  '6': 'Combine logs: log₂(x(x + 6)) = 4. Solve x² + 6x = 16 to get x = 2 or -8; only x = 2 is in the domain.',
  '7': 'Isolate absolute value: |2x - 4| = 8. Solve 2x - 4 = 8 and 2x - 4 = -8 to get x = 6 or -2.',
  '8': 'Rewrite with base 3: 3^(-2x) = 3³. Then -2x = 3, so x = -3/2.',
  '9': 'Rewrite with base 2: 2^(4 - 4x) = 2^-3. Then 4 - 4x = -3, so x = 7/4.',
  '10': 'Isolate the power: (x - 15)^(3/5) = -8. The fifth root is -2, and (-2)^5 = -32, so x = -17.',
  '11': 'Factor x^(4/5)(1 + 3x) = 0. Then x = 0 or x = -1/3.',
  '12': 'With x ≠ 0,1, multiply by x(x - 1): 1 = (x - 1)². The possible values are 0 and 2, but x = 0 is excluded, so x = 2.',
  '13': 'The matching fractions cancel, leaving 0 = -1/(x - 1), which is impossible. There is no solution.',
  '14': 'Use division before subtraction: 8 - 16 ÷ 4 = 8 - 4 = 4.',
  '15': '81^(1/4) is the principal fourth root of 81, which is 3.',
  '16': 'Without parentheses, the exponent applies to 4 first: -4² = -(16) = -16.',
  '17': 'Because the negative is inside parentheses, (-3)³ = -27.',
  '18': 'Divide by a fraction by multiplying by the reciprocal: 1 ÷ 5/9 = 9/5.',
  '19': '(-4)^4 has an even exponent, so the result is positive: 256.',
  '20': 'A -1 exponent means reciprocal: 29^-1 = 1/29.',
  '21': 'Factor 32 = 16·2. The fourth root of 16 is 2, so the simplified result is 2 fourth-root 2.',
  '22': '8^(1/3) = 2, and the negative exponent makes the reciprocal, so 8^(-1/3) = 1/2.',
  '23': 'log₄(64) asks for the exponent on 4 that gives 64. Since 4³ = 64, the answer is 3.',
  '24': '1/16 = 2^-4, so log₂(1/16) = -4.',
  '25': 'ln and e are inverse operations, so ln(e^4) = 4.',
  '26': 'Quadratic parent: domain all real, range y ≥ 0, vertex (0,0), opens up.',
  '27': 'Identity linear parent: domain and range all real, passes through (0,0), rises left to right.',
  '28': 'Log base 2 parent: domain x > 0, range all real, vertical asymptote x = 0, point (1,0).',
  '29': 'Exponential parent 3^x: domain all real, range y > 0, horizontal asymptote y = 0, point (0,1).',
  '30': 'Square-root parent: starts at (0,0), domain x ≥ 0, range y ≥ 0.',
  '31': 'Cubic parent: S-shaped through (0,0), with domain and range all real.',
  '32': 'Reciprocal parent: asymptotes x = 0 and y = 0, domain and range exclude 0, branches in Quadrants I and III.',
  '33': 'Reciprocal-squared parent: asymptotes x = 0 and y = 0, domain excludes 0, range y > 0, branches above the x-axis.',
  '34': 'Common-log parent: domain x > 0, range all real, vertical asymptote x = 0, point (1,0).',
  '35': 'Absolute value parent: V shape with vertex (0,0), domain all real, range y ≥ 0.',
  '36': 'Cube-root parent: passes through (0,0), with domain and range all real.',
  '37': 'The line y = (4/3)x - 2 has slope 4/3, y-intercept (0,-2), and rises left to right.'
};
