window.GRAPH_DATA = [
  {id:'g-1a',parentType:'linear',domain:'(-infinity, infinity)',range:'(-infinity, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'passes through (0, 0)',graphNotes:'Parent line with slope 1.',solutionGraphPlaceholder:'Stage 2 may add a y = x thumbnail.'},
  {id:'g-1b',parentType:'absolute value',domain:'(-infinity, infinity)',range:'[0, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'vertex (0, 0)',graphNotes:'V-shape opening up.',solutionGraphPlaceholder:'Stage 2 may add an absolute value thumbnail.'},
  {id:'g-1c',parentType:'quadratic',domain:'(-infinity, infinity)',range:'[0, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'vertex (0, 0)',graphNotes:'Parabola opens up.',solutionGraphPlaceholder:'Stage 2 may add a parabola thumbnail.'},
  {id:'g-1d',parentType:'cubic',domain:'(-infinity, infinity)',range:'(-infinity, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'center/inflection point (0, 0)',graphNotes:'S-curve increasing through the origin.',solutionGraphPlaceholder:'Stage 2 may add a cubic thumbnail.'},
  {id:'g-1e',parentType:'square root',domain:'[0, infinity)',range:'[0, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'starting point (0, 0)',graphNotes:'Starts at the origin and increases to the right.',solutionGraphPlaceholder:'Stage 2 may add a square-root thumbnail.'},
  {id:'g-1f',parentType:'cube root',domain:'(-infinity, infinity)',range:'(-infinity, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'center point (0, 0)',graphNotes:'Sideways S-shape through the origin.',solutionGraphPlaceholder:'Stage 2 may add a cube-root thumbnail.'},
  {id:'g-1g',parentType:'reciprocal',domain:'(-infinity, 0) union (0, infinity)',range:'(-infinity, 0) union (0, infinity)',verticalAsymptote:'x = 0',horizontalAsymptote:'y = 0',keyPoint:'branches in Quadrants I and III',graphNotes:'Two branches approach both axes.',solutionGraphPlaceholder:'Stage 2 may add a reciprocal thumbnail.'},
  {id:'g-1h',parentType:'reciprocal squared',domain:'(-infinity, 0) union (0, infinity)',range:'(0, infinity)',verticalAsymptote:'x = 0',horizontalAsymptote:'y = 0',keyPoint:'branches in Quadrants I and II',graphNotes:'Both branches stay above the x-axis.',solutionGraphPlaceholder:'Stage 2 may add a reciprocal-squared thumbnail.'},
  {id:'g-1i',parentType:'exponential',domain:'(-infinity, infinity)',range:'(0, infinity)',verticalAsymptote:'none',horizontalAsymptote:'y = 0',keyPoint:'passes through (0, 1)',graphNotes:'Increases and approaches the x-axis on the left.',solutionGraphPlaceholder:'Stage 2 may add an exponential thumbnail.'},
  {id:'g-1j',parentType:'logarithmic',domain:'(0, infinity)',range:'(-infinity, infinity)',verticalAsymptote:'x = 0',horizontalAsymptote:'none',keyPoint:'passes through (1, 0)',graphNotes:'Increases and approaches the y-axis from the right.',solutionGraphPlaceholder:'Stage 2 may add a logarithmic thumbnail.'},
  {id:'g-2a',parentType:'quadratic',domain:'(-infinity, infinity)',range:'[-1, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'vertex (-2, -1)',graphNotes:'Opens up; x-intercepts (-3, 0), (-1, 0); y-intercept (0, 3).',solutionGraphPlaceholder:'Stage 2 may add transformed quadratic rendering.'},
  {id:'g-2b',parentType:'absolute value',domain:'(-infinity, infinity)',range:'(-infinity, 4]',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'vertex (2, 4)',graphNotes:'Opens down; x-intercepts (-2, 0), (6, 0); y-intercept (0, 2).',solutionGraphPlaceholder:'Stage 2 may add transformed absolute value rendering.'},
  {id:'g-2c',parentType:'logarithmic',domain:'(3, infinity)',range:'(-infinity, infinity)',verticalAsymptote:'x = 3',horizontalAsymptote:'none',keyPoint:'x-intercept (4, 0)',graphNotes:'Shift right 3 from y = log_2(x).',solutionGraphPlaceholder:'Stage 2 may add transformed logarithm rendering.'},
  {id:'g-2d',parentType:'reciprocal',domain:'(-infinity, -4) union (-4, infinity)',range:'(-infinity, 0) union (0, infinity)',verticalAsymptote:'x = -4',horizontalAsymptote:'y = 0',keyPoint:'shift left 4',graphNotes:'Branches approach x = -4 and y = 0.',solutionGraphPlaceholder:'Stage 2 may add transformed reciprocal rendering.'},
  {id:'g-2e',parentType:'square root',domain:'[0, infinity)',range:'(-infinity, 1]',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'starting point (0, 1)',graphNotes:'Reflect over the x-axis, then shift up 1.',solutionGraphPlaceholder:'Stage 2 may add transformed square-root rendering.'},
  {id:'g-2f',parentType:'cubic',domain:'(-infinity, infinity)',range:'(-infinity, infinity)',verticalAsymptote:'none',horizontalAsymptote:'none',keyPoint:'center/inflection point (-1, 0)',graphNotes:'Shift left 1 from y = x^3.',solutionGraphPlaceholder:'Stage 2 may add transformed cubic rendering.'}
];
